import img11 from '../../assets/haldi.webp';
export const ProductList = [
    {
        id: 5803,
        name: 'Dil Bahar BLACK PEPPER',
        image: img11,
        category: 'Spices',
        link: '/product/5803',
        description: "A select blend of 13 spices go into this grand old universal taste enhancer. Being chilli based, it provides an exotic red gravy to dishes.It is widely used all over India on account of its being a less pungent garam masala. Fennel, Tejpatta (Cinnamon leaves) and Trifala imparts a cooling effect to this blend.",
        packaging: '15 gms / 25 gms / 50 gms / 100 gms / 200 gms / Jar 1 kg',
        usage: 'It is used essentially for preparing vegetarian dishes requiring a gravy. Gujaratis and Marwaris normally use it in lentils (dal) and for filling in snacks such as samosa, usal, patra, farsan etc.',
    },
    {
        id: 5822,
        name: 'Dil Bahar DEGGI MIRCH',
        image: img11,
        category: 'Spices',
        link: '/product/5822',
        description: "A select blend of 13 spices go into this grand old universal taste enhancer. Being chilli based, it provides an exotic red gravy to dishes.It is widely used all over India on account of its being a less pungent garam masala. Fennel, Tejpatta (Cinnamon leaves) and Trifala imparts a cooling effect to this blend.",
        packaging: '15 gms / 25 gms / 50 gms / 100 gms / 200 gms / Jar 1 kg',
        usage: 'It is used essentially for preparing vegetarian dishes requiring a gravy. Gujaratis and Marwaris normally use it in lentils (dal) and for filling in snacks such as samosa, usal, patra, farsan etc.',
    },
    {
        id: 5823,
        name: 'Dil Bahar DHANIA POWDER',
        image: img11,
        category: 'Spices',
        link: '/product/5823',
        description: "A select blend of 13 spices go into this grand old universal taste enhancer. Being chilli based, it provides an exotic red gravy to dishes.It is widely used all over India on account of its being a less pungent garam masala. Fennel, Tejpatta (Cinnamon leaves) and Trifala imparts a cooling effect to this blend.",
        packaging: '15 gms / 25 gms / 50 gms / 100 gms / 200 gms / Jar 1 kg',
        usage: 'It is used essentially for preparing vegetarian dishes requiring a gravy. Gujaratis and Marwaris normally use it in lentils (dal) and for filling in snacks such as samosa, usal, patra, farsan etc.',
    },
    {
        id: 5826,
        name: 'Dil Bahar HALDI POWDER',
        image: img11,
        category: 'Spices',
        link: '/product/5826',
        description: "A select blend of 13 spices go into this grand old universal taste enhancer. Being chilli based, it provides an exotic red gravy to dishes.It is widely used all over India on account of its being a less pungent garam masala. Fennel, Tejpatta (Cinnamon leaves) and Trifala imparts a cooling effect to this blend.",
        packaging: '15 gms / 25 gms / 50 gms / 100 gms / 200 gms / Jar 1 kg',
        usage: 'It is used essentially for preparing vegetarian dishes requiring a gravy. Gujaratis and Marwaris normally use it in lentils (dal) and for filling in snacks such as samosa, usal, patra, farsan etc.',
    },
    {
        id: 5830,
        name: 'Dil Bahar JEERA POWDER',
        image: img11,
        category: 'Spices',
        link: '/product/5830',
        description: "A select blend of 13 spices go into this grand old universal taste enhancer. Being chilli based, it provides an exotic red gravy to dishes.It is widely used all over India on account of its being a less pungent garam masala. Fennel, Tejpatta (Cinnamon leaves) and Trifala imparts a cooling effect to this blend.",
        packaging: '15 gms / 25 gms / 50 gms / 100 gms / 200 gms / Jar 1 kg',
        usage: 'It is used essentially for preparing vegetarian dishes requiring a gravy. Gujaratis and Marwaris normally use it in lentils (dal) and for filling in snacks such as samosa, usal, patra, farsan etc.',
    },
    {
        id: 5831,
        name: 'Dil Bahar KASHMIRI MIRCH POWDER',
        image: img11,
        category: 'Spices',
        link: '/product/5831',
        description: "A select blend of 13 spices go into this grand old universal taste enhancer. Being chilli based, it provides an exotic red gravy to dishes.It is widely used all over India on account of its being a less pungent garam masala. Fennel, Tejpatta (Cinnamon leaves) and Trifala imparts a cooling effect to this blend.",
        packaging: '15 gms / 25 gms / 50 gms / 100 gms / 200 gms / Jar 1 kg',
        usage: 'It is used essentially for preparing vegetarian dishes requiring a gravy. Gujaratis and Marwaris normally use it in lentils (dal) and for filling in snacks such as samosa, usal, patra, farsan etc.',
    },
    {
        id: 5836,
        name: 'Dil Bahar KASOORI METHI',
        image: img11,
        category: 'Herbs',
        link: '/product/5836',
        description: "A select blend of 13 spices go into this grand old universal taste enhancer. Being chilli based, it provides an exotic red gravy to dishes.It is widely used all over India on account of its being a less pungent garam masala. Fennel, Tejpatta (Cinnamon leaves) and Trifala imparts a cooling effect to this blend.",
        packaging: '15 gms / 25 gms / 50 gms / 100 gms / 200 gms / Jar 1 kg',
        usage: 'It is used essentially for preparing vegetarian dishes requiring a gravy. Gujaratis and Marwaris normally use it in lentils (dal) and for filling in snacks such as samosa, usal, patra, farsan etc.',
    },
    {
        id: 5833,
        name: 'Dil Bahar LALMIRCH',
        image: img11,
        category: 'Spices',
        link: '/product/5833',
        description: "A select blend of 13 spices go into this grand old universal taste enhancer. Being chilli based, it provides an exotic red gravy to dishes.It is widely used all over India on account of its being a less pungent garam masala. Fennel, Tejpatta (Cinnamon leaves) and Trifala imparts a cooling effect to this blend.",
        packaging: '15 gms / 25 gms / 50 gms / 100 gms / 200 gms / Jar 1 kg',
        usage: 'It is used essentially for preparing vegetarian dishes requiring a gravy. Gujaratis and Marwaris normally use it in lentils (dal) and for filling in snacks such as samosa, usal, patra, farsan etc.',
    },
    {
        id: 5848,
        name: 'Dil Bahar WHITEPEPPER',
        image: img11,
        category: 'Spices',
        link: '/product/5848',
        description: "A select blend of 13 spices go into this grand old universal taste enhancer. Being chilli based, it provides an exotic red gravy to dishes.It is widely used all over India on account of its being a less pungent garam masala. Fennel, Tejpatta (Cinnamon leaves) and Trifala imparts a cooling effect to this blend.",
        packaging: '15 gms / 25 gms / 50 gms / 100 gms / 200 gms / Jar 1 kg',
        usage: 'It is used essentially for preparing vegetarian dishes requiring a gravy. Gujaratis and Marwaris normally use it in lentils (dal) and for filling in snacks such as samosa, usal, patra, farsan etc.',
    },
];